services:

  nginx:
    image: nginx:latest
    container_name: job07-nginx
    ports:
      - "8080:80"
    volumes:
      - ./site:/usr/share/nginx/html

  ftp:
    image: fauria/vsftpd
    container_name: job07-ftp
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      FTP_USER: admin
      FTP_PASS: admin123
      PASV_ADDRESS: 192.168.0.138
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110
    volumes:
      - ./site:/home/vsftpd/admin
